Update CCM Dependency Packages
chocolatey/choco-quickstart-scripts pull request #195
Opened 2023-06-26 20:05 UTC by ryanrichter94

## Description Of Changes
Update CCM dependency packages versions.

## Motivation and Context
Keep guide as up to date as possible.

## Testing
1. Tested on local VM

### Operating Systems Testing
- Windows Server 2022

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [X] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [X] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [X] All new and existing tests passed?
* [X] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

Fixes #194

2023-06-30 10:17 UTC, JPRuskin approved these changes

2023-07-02 13:11 UTC, TonyHCIR approved these changes

2023-07-02 13:11 UTC, TonyHCIR requested changes
T

2023-07-02 13:13 UTC, TonyHCIR approved these changes

2023-07-06 13:51 UTC, merged