Remove Ansible Callout From README
chocolatey/choco-quickstart-scripts pull request #264
Opened 2024-08-30 16:50 UTC by ryanrichter94

## Description Of Changes
- Removed Ansible code from connect section of README
- Change Internalize some new packages link to point to correct name of Jenkins jobs

## Motivation and Context
No need for Ansible callout as we have a separate enviornment for Ansible users.

## Testing
1. Local VM QSG build

### Operating Systems Testing
- Windows Server 2022

## Change Types Made
* ~[ ] Bug fix (non-breaking change).~
* [X] Feature / Enhancement (non-breaking change).
* ~[ ] Breaking change (fix or feature that could cause existing functionality to change).~
* ~[ ] Documentation changes.~
* ~[ ] PowerShell code changes.~

## Change Checklist
* ~[ ] Requires a change to the documentation.~
* ~[ ] Documentation has been updated.~
* ~[ ] Tests to cover my changes, have been added.~
* ~[ ] All new and existing tests passed?~
* ~[ ] PowerShell code changes: PowerShell v3 compatibility checked?~

## Related Issue
Fixes #263

2024-08-30 17:26 UTC, ryanrichter94 commented
Looks after changes:
![image](https://github.com/user-attachments/assets/e8ea1de3-2d56-4b23-9ddf-38dd5640688e)

2024-08-30 17:36 UTC, steviecoaster requested changes

2024-08-30 17:36 UTC, steviecoaster commented on scripts/ReadmeTemplate.html.j2
>  <h2 id="connect">Adding Computers to Chocolatey Central Management</h2>
You missed this clear down to the closing </div>

2024-09-05 14:40 UTC, ryanrichter94 commented
Closing this PR and re-doing it.

2024-09-05 14:40 UTC, closed without merging