Move Jenkins scripts to root of System Drive
chocolatey/choco-quickstart-scripts pull request #80
Opened 2021-09-23 18:33 UTC by steviecoaster

This PR will fix #79 by moving the Jenkins scripts to the root of the System Drive into  a `scripts` folder. 

This brings parity with QDE appliance.

2021-09-23 18:35 UTC, steviecoaster commented
Remove from DRAFT once tested and approved

2021-09-23 20:21 UTC, adilio requested changes
Once the trailing slash suggestion is fixed, we're good to go.

You'll need to rebase first, but after that the code is tested and good to go.

2021-09-23 20:21 UTC, adilio commented on Start-C4bJenkinsSetup.ps1
> +$systemRoot = $env:SystemDrive
```suggestion
$systemRoot = $env:SystemDrive + '\'
```

2021-09-24 13:29 UTC, ryanrichter94 approved these changes
LGTM 🚀

2021-09-24 15:16 UTC, adilio approved these changes
LGTM, and tested! 🚀

2021-09-24 15:16 UTC, merged